sudo: false
language: java

jdk:
  - oraclejdk8

env:
  global:
  - secure: mp1gRwPKlm1Z97eDzrFE1U7KRyIHI/qwBKGbJT9TsLOWYy3sREO61npHzbsFF+/DhJJ9y7/pLmDUycFhTg9bO2DBo4A1ZL/2NNd/ISUEMC1xdKgh8Bodp54u8xG42ez/CT3SmWCHFkraKm6ovjp+W5+4ifmLCb1rV7IqZ1Phu3JOjFeDOJPw0AG29MQmUaKdKB1D6wXhIVXTNPAPiAMBtdElfPZgc984v2b2cIou0/9w3wRupHegJi9VcOUtWpd8LJr0lWIT3w77N99TMNuJZ1rcoII+FioJt2pnE+uKJ52aRayut43/UJiLz0yd3dmD1gEdOcFAC6004IWm/yJuz1ITzUu4M/V26yLDIDvnOyrstm7PUZapNerk4XbxAxa2rYRkgunkGPM1JjgxuGcJzm8v701COC2eScOHLW9ZBlF8TvOgkoxgsYcaaJNJxTuvJ5HgSGOes76ZrzLfZba59YnQEhiVxFW+oKVZaOO2q7YYMCayruVFZuvHW6Vv3g5Ocm7oPFmYTBt4slsoEG3XN35vnswgdvj2PqrU2jjkI8+MSM+fEuVhSfr0scmtydOaSyx/2BZaron+ymU6oPMwVfLeLvfWVh0wmVhbQXqIqmPXqrtDN53uZl00L1hOJza7vKk/moxYfJqKPgrC/JvVpE2eJC0bEKs3uRKf807RBvs=


before_script:
  - pip install --user codecov

after_success:
  - codecov
